src/obb/blackboard/models/__init__.py
__all__ = [
    "BlackboardRoom",
    "BlackBoardRoomData",
    "Lecture",
    "LectureData",
    "LecturePage",
    "LecturePageData",
    "LectureSession",
]

from .blackboard_room import BlackboardRoom, BlackBoardRoomData
from .lecture import Lecture, LectureData
from .lecture_page import LecturePage, LecturePageData
from .lecture_session import LectureSession

src/obb/blackboard/models/blackboard_room.py
from dataclasses import dataclass

from dataclasses_json import LetterCase, dataclass_json

from obb.ext import db
from obb.tools.models.BaseModel import BaseModel
from .defaults import (
    default_blackboard_visibility,
    default_draw_height,
    default_draw_width,
)
from .wrappers.blackboard_room import BlackboardRoomWrapper


def create_default_id() -> str:
    from obb.tools import id_generator

    return id_generator(12)


@dataclass_json(letter_case=LetterCase.CAMEL)
@dataclass
class BlackBoardRoomData:
    id: str
    name: str

    draw_height: int
    draw_width: int


class BlackboardRoom(db.Model, BaseModel, BlackboardRoomWrapper):
    id = db.Column(db.String, primary_key=True, default=create_default_id)
    name = db.Column(db.String, nullable=False, index=True)

    creator_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    creator = db.relationship("User")

    constraint_creator_name = db.UniqueConstraint(creator_id, name)

    draw_height = db.Column(
        db.Integer,
        nullable=False,
        default=default_draw_height,
        server_default=str(default_draw_height),
    )

    draw_width = db.Column(
        db.Integer,
        nullable=False,
        default=default_draw_width,
        server_default=str(default_draw_width),
    )

    visibility = db.Column(
        db.String,
        nullable=False,
        server_default=default_blackboard_visibility,
        default=default_blackboard_visibility,
    )

    is_invisible = db.Column(
        db.Boolean, nullable=False, server_default="0", default=False
    )

    sessions = db.relationship("LectureSession", lazy=True)

    def get_data(self) -> BlackBoardRoomData:
        return BlackBoardRoomData(
            id=self.id,
            name=self.name,
            draw_height=self.draw_height,
            draw_width=self.draw_width,
        )

src/obb/blackboard/models/defaults.py
from obb.tools.enum import ExtendEnum


class Visibility(ExtendEnum):
    CREATOR_ONLY = "creator_only"
    PUBLIC = "public"


#  Global
default_draw_height = 256
default_draw_width = 1024

assert default_draw_width > 1, "default_draw_height must be greater than 1"
assert default_draw_width > 1, "default_draw_width must be greater than 1"

# Blackboard
default_blackboard_visibility = Visibility.PUBLIC.value

# Lecture-Session
default_lecture_session_visibility = Visibility.CREATOR_ONLY.value

src/obb/blackboard/forms/lecture.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

from obb.tools.forms import BaseDataForm


class ShortCreateLectureForm(FlaskForm, BaseDataForm):
    lecture_name = StringField("Lecture", validators=[DataRequired(), Length(max=128)])
    submit = SubmitField("Create")


class CreateLectureForm(FlaskForm, BaseDataForm):
    lecture_name = StringField("Lecture", validators=[DataRequired(), Length(max=128)])
    submit = SubmitField("Create")

src/obb/blackboard/forms/room.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Length

from obb.blackboard.models.defaults import Visibility, default_blackboard_visibility
from obb.tools.forms import BaseDataForm


class ShortCreateRoomForm(FlaskForm, BaseDataForm):
    room_name = StringField("Room", validators=[DataRequired(), Length(max=128)])
    submit = SubmitField("Create")


class CreateRoomForm(FlaskForm, BaseDataForm):
    room_name = StringField("Room", validators=[DataRequired(), Length(max=128)])
    visibility = SelectField(
        "Visibility",
        default=default_blackboard_visibility,
        choices=Visibility.list(),
        validators=[DataRequired()],
    )
    submit = SubmitField("Create")


class RoomSettingsForm(FlaskForm, BaseDataForm):
    draw_height = IntegerField("Board-Height", validators=[DataRequired()])
    draw_width = IntegerField("Board-Width", validators=[DataRequired()])
    visibility = SelectField(
        "Visibility",
        default=default_blackboard_visibility,
        choices=Visibility.list(),
        validators=[DataRequired()],
    )
    submit = SubmitField("Update")

src/obb/blackboard/forms/session.py
import datetime

from flask_wtf import FlaskForm
from wtforms import StringField, DateTimeField, IntegerField, SubmitField
from wtforms.validators import DataRequired, Length

from obb.tools.forms import BaseDataForm


class CreateSessionForm(FlaskForm, BaseDataForm):
    name = StringField("Name", validators=[DataRequired(), Length(max=128)])

    room_name = StringField("Room", validators=[DataRequired()])

    start_time = DateTimeField(
        "Start DateTime", default=datetime.datetime.now, validators=[DataRequired()]
    )
    duration = IntegerField("Duration", default=100, validators=[DataRequired()])

    lecture_name = StringField("Lecture", validators=[DataRequired()])

    submit = SubmitField("Create")

src/obb/blackboard/__init__.py
from . import views, events, js

src/obb/blackboard/datas/__init__.py
__all__ = ['StrokeData']

from .stroke_data import StrokeData

src/obb/blackboard/events/__init__.py
from . import connect_disconnect
from . import room_add_sketch
from . import room_clear_sketch
from . import room_create_page
from . import room_get_content
from . import room_get_page
from . import room_get_sketch
from . import room_get_users
from . import room_join
from . import room_moveto_page
from . import room_remove_page
from . import room_setcurrent_page
from . import room_update
from . import room_update_content
from . import room_update_user

src/obb/blackboard/memory/__init__.py
__all__ = [
    "room_memory",
    "MemoryBlackboardRoom",
    "MemoryBlackboardRoomData",
    "user_session_memory",
    "MemorySessionUser",
    "MemorySessionUserData",
    "lecture_page_memory",
    "MemoryLecturePage",
    "MemoryLecturePageData",
    "user_memory",
    "MemoryUser",
]

from obb.tools.MemDb import MemDb

from .blackboard_room import MemoryBlackboardRoom, MemoryBlackboardRoomData
from .user_session import MemorySessionUser, MemorySessionUserData
from .lecture_page import MemoryLecturePage, MemoryLecturePageData
from .user import MemoryUser

room_memory = MemDb[str, MemoryBlackboardRoom]()

user_memory = MemDb[str, MemoryUser]()

user_session_memory = MemDb[str, MemorySessionUser]()

lecture_page_memory = MemDb[str, MemoryLecturePage]()

src/obb/blackboard/views/__init__.py
from flask import Blueprint
from ..ext import namespace

bp = Blueprint('blackboard', __name__, url_prefix=namespace)

# Home
from . import home

# Rooms
from . import room
from . import room_link

# Sessions
from . import session

# Lecturs
from . import lecture

src/obb/blackboard/views/functions.py
from flask import session

from obb.blackboard.memory import (
    user_memory,
    MemoryUser,
    user_session_memory,
    MemorySessionUser,
)
from obb.blackboard.models import BlackboardRoom
from obb.tools import id_generator
from obb.users.models import User


def get_mem_user_session(room: BlackboardRoom):
    mem_user: MemoryUser = user_memory.get(session.get("user_id", None))
    if not mem_user:
        mem_user = MemoryUser()
        user_memory.add(mem_user.id, mem_user)
        session["user_id"] = mem_user.id

    mem_user_session_id = mem_user.sessions.get(room.id)
    mem_user_session = user_session_memory.get(mem_user_session_id)

    sid = mem_user_session_id or id_generator(24)
    if not mem_user_session:
        mem_user_session = MemorySessionUser(sid, User.get_current_id())
        user_session_memory.add(sid, mem_user_session)
        mem_user.sessions[room.id] = sid

    return mem_user_session

src/obb/blackboard/views/home.py
import datetime

from flask import render_template

from . import bp
from ..models import LectureSession
from ...api import ApiToken


@bp.route("/", methods=["GET", "POST"])
def home():
    l_session: LectureSession
    l_sessions = [
        l_session
        for l_session in LectureSession.get_lectures()
        if l_session.visibility == "public"
        if l_session.end_time > datetime.datetime.utcnow()
        if l_session.is_open()
    ]

    token = ApiToken.create_token()

    return render_template("blackboard/home.html", l_sessions=l_sessions, token=token)

src/obb/blackboard/views/lecture.py
from flask import flash, redirect, url_for, render_template, send_file, request
from flask_login import login_required, current_user

from . import bp
from ..forms.lecture import CreateLectureForm
from ..models import Lecture, BlackboardRoom, LecturePage, LectureSession
from ..models.defaults import Visibility
from ...ext import db


@bp.route("/lecture/create", methods=["GET", "POSt"])
@login_required
def lecture_create():
    def render(create_form):
        return render_template(
            "blackboard/lecture/create.html", create_form=create_form
        )

    create_form = CreateLectureForm()

    if create_form.validate_on_submit():
        lecture_name = create_form.lecture_name.data

        lecture = Lecture.get_by_name(lecture_name)
        if lecture:
            flash("Lecture already exist", "error")
            return render(create_form)

        lecture = Lecture()
        lecture.name = lecture_name
        lecture.creator = current_user

        lecture_page = LecturePage.create(lecture)

        db.session.add(lecture)
        db.session.add(lecture_page)
        db.session.commit()

        return redirect(url_for("blackboard.room_list"))

    return render(create_form)


@bp.route("/lecture/<lecture_id>", methods=["GET", "POSt"])
@login_required
def lecture_edit(lecture_id):
    lecture = Lecture.get(lecture_id)

    if lecture.creator != current_user:
        flash("Not allowed")
        return redirect(url_for("blackboard.room_list"))

    if not lecture:
        flash("lecture not found")
        return redirect(url_for("blackboard.home"))

    room_id = request.args.get("r")
    room = BlackboardRoom.get(room_id)
    if not room:
        room = lecture.edit_room
        if not room:
            room = BlackboardRoom()
            room.name = f"LectureRoom.{lecture.name}"
            room.creator = current_user
            room.is_invisible = True
            lecture.edit_room = room
            db.session.add(room)
            db.session.commit()

    current_session = room.get_current_lecture_session()
    if not current_session:
        current_session = LectureSession()
        current_session.name = f"Edit Session for {lecture.name}"
        current_session.visibility = Visibility.CREATOR_ONLY.value
        current_session.room = room
        current_session.lecture = lecture
        current_session.maintainer = current_user
        db.session.add(current_session)
        db.session.commit()

    return redirect(url_for("blackboard.link_user", room_id=room.id))


@bp.route("/lecture/<lecture_id>/download", methods=["GET", "POSt"])
@login_required
def lecture_download(lecture_id: int):
    lecture = Lecture.get(lecture_id)
    if current_user != lecture.creator:
        return

    fname, fpath = lecture.create_export_file()
    return send_file(
        fpath, attachment_filename=fname, as_attachment=True, mimetype="application/zip"
    )

src/obb/blackboard/views/room.py
import datetime

from flask import flash, redirect, url_for, render_template, request
from flask_login import login_required, current_user

from . import bp
from ..forms.lecture import ShortCreateLectureForm
from ..forms.room import ShortCreateRoomForm, CreateRoomForm
from ..forms.session import CreateSessionForm
from ..models import BlackboardRoom, LectureSession, Lecture
from ...ext import db


@bp.route("/room", methods=["GET", "POST"])
@login_required
def room_list():
    create_room_form = ShortCreateRoomForm()
    create_lecture_form = ShortCreateLectureForm()
    create_session_form = CreateSessionForm()

    rooms = BlackboardRoom.get_rooms()
    lectures = Lecture.get_lectures()

    # Todo: Query ?
    lecture_sessions = [
        l_session
        for l_session in LectureSession.get_lectures(current_user.id)
        if l_session.end_time > datetime.datetime.utcnow()
    ]

    return render_template(
        "blackboard/rooms.html",
        create_room_form=create_room_form,
        create_lecture_form=create_lecture_form,
        create_session_form=create_session_form,
        rooms=rooms,
        lectures=lectures,
        lecture_sessions=lecture_sessions,
    )


@bp.route("/room/create", methods=["GET", "POST"])
@login_required
def room_create():
    def render(create_form):
        return render_template("blackboard/room/create.html", create_form=create_form)

    create_form = CreateRoomForm()

    if create_form.validate_on_submit():
        room_name = create_form.room_name.data

        room = BlackboardRoom.get_by_name(room_name)
        if room:
            flash("Room already exist")
            return render(create_form)

        room = BlackboardRoom()
        room.name = room_name
        room.creator = current_user
        room.visibility = create_form.visibility.data

        db.session.add(room)
        db.session.commit()

        return redirect(url_for("blackboard.room_list"))

    return render(create_form)

src/obb/blackboard/views/room_link.py
from flask import flash, redirect, url_for, render_template, request
from flask_login import current_user, login_required

from . import bp
from .functions import get_mem_user_session
from ..forms.room import RoomSettingsForm
from ..models import BlackboardRoom
from ...api import ApiToken
from ...ext import db


@bp.route("/link/", methods=["GET", "POST"])
@bp.route("/link/blackboard", methods=["GET", "POST"])
def link_blackboard():
    room_id = request.args.get("r") or request.args.get("room_id")

    room = BlackboardRoom.get(room_id)
    if not room:
        flash("room does not exist")
        return redirect(url_for("blackboard.home"))

    l_session = room.get_current_lecture_session()
    if not l_session:
        flash("room is closed")
        return redirect(url_for("blackboard.home"))

    mem_user_session = get_mem_user_session(room)

    token = ApiToken.create_token(sid=mem_user_session.sid)

    return render_template(
        "blackboard/mode_blackboard.html", l_session=l_session, room=room, token=token
    )


@bp.route("/link/user", methods=["GET", "POST"])
@login_required
def link_user():
    room_id = request.args.get("r") or request.args.get("room_id")
    room = BlackboardRoom.get(room_id)

    if room is None:
        flash("Room does not exist")
        return redirect(url_for("blackboard.room_list"))

    l_session = room.get_current_lecture_session()
    if not l_session:
        flash("room is closed")
        return redirect("blackboard.home")

    if room.creator_id != current_user.id:
        flash("you have no access to the page")
        return redirect(url_for("blackboard.room_list"))

    edit_form = RoomSettingsForm()

    if edit_form.validate_on_submit():
        edit_form.write_data(room)
        db.session.commit()
        return redirect(url_for("blackboard.link_user", room_id=room.id))

    edit_form.read_data(room)

    mem_user_session = get_mem_user_session(room)

    mem_user_session.mode = "user"
    mem_user_session.allow_draw = True
    mem_user_session.allow_new_page = True

    token = ApiToken.create_token(sid=mem_user_session.sid)

    return render_template(
        "blackboard/mode_user.html",
        l_session=l_session,
        room=room,
        token=token,
        edit_form=edit_form,
    )

src/obb/blackboard/views/session.py
from flask import flash, redirect, url_for, render_template
from flask_login import login_required, current_user

from . import bp
from ..forms.session import CreateSessionForm
from ..models import BlackboardRoom, LectureSession, Lecture
from ..models.defaults import Visibility
from ...ext import db


@bp.route("/session/create", methods=["GET", "POST"])
@login_required
def session_create():
    def render(form, rooms, lectures):
        return render_template(
            "blackboard/session/create.html", form=form, rooms=rooms, lectures=lectures
        )

    rooms = BlackboardRoom.get_rooms()
    lectures = Lecture.get_lectures()

    form = CreateSessionForm()
    if form.validate_on_submit():

        room = BlackboardRoom.get_by_name(form.room_name.data)
        lecture = Lecture.get_by_name(form.lecture_name.data)

        fail_count = 0

        if not room:
            flash("room does not exist", "error")
            fail_count += 1

        if not lecture:
            flash("lecture does not exist", "error")
            fail_count += 1

        if fail_count:
            return render(form, rooms, lectures)

        lecture_session = LectureSession()
        lecture_session.maintainer = current_user
        form.write_data(lecture_session)

        lecture_session.lecture = lecture
        lecture_session.room = room
        lecture_session.visibility = Visibility.PUBLIC.value

        db.session.add(lecture_session)

        if room.intersect_lecture(lecture_session.start_time, lecture_session.duration):
            flash("Session intersects", "error")
            return render(form, rooms, lectures)

        room.sessions.append(lecture_session)

        db.session.commit()

        return redirect(url_for("blackboard.room_list"))

    return render(form, rooms, lectures)

src/obb/templates/blackboard/connect_to.html
{% extends 'blackboard/layout.html' %}
{% from 'form.html' import show_form %}

{% block col %}
    <div class="col mt-3">
        <div class="card">
            <div class="card-header">
                Create
            </div>
            <div class="card-body">
                {{ show_form(create_form) }}
            </div>
        </div>

    </div>
    <div class="col mt-3">
        <div class="card">
            <div class="card-header">Rooms</div>
            <div class="card-body">
                <ul id="roomList" class="nav flex-column">
                    {% for room in rooms %}
                        <li id="room-{{ room.room_id }}" class="nav-item">
                            <a class="nav-link"
                               href="{{ url_for('blackboard.connect_to_room',room_id=room.id) }}">{{ room.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col">
    </div>
{% endblock %}

src/obb/templates/blackboard/home.html
{% extends 'blackboard/layout.html' %}
{% from 'form.html' import show_form %}

{% block col %}
    <div class="col mt-3">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Lecture</th>
                <th scope="col">User</th>
                <th scope="col">Room</th>
                <th scope="col">Start-Time</th>
                <th scope="col">End-Time</th>
                <th scope="col">Duration</th>
            </tr>
            </thead>
            <tbody>
            {% for l_session in l_sessions %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td>
                        <a href="{{ url_for('blackboard.link_blackboard',r=l_session.room.id) }}">
                            {{ l_session.name }}</a></td>
                    <td>{{ l_session.lecture.name }} </td>
                    <td>{{ l_session.maintainer.username }} </td>
                    <td>{{ l_session.room.name }} </td>
                    <td>{{ l_session.start_time | df }} </td>
                    <td>{{ l_session.end_time | df }} </td>
                    <td>{{ l_session.duration }} min</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

src/obb/templates/blackboard/layout.html
{% extends 'layout.html' %}

{% block meta %}
    {% if token %}
        <meta content="{{ token.encode() }}" name="session-token"/>
    {% endif %}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blackboard/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blackboard/toolbox.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blackboard/blackboard.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blackboard/blackboard.style.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='colorPicker/colorPick.css') }}">

    {% block blackboard_css %}
    {% endblock %}
{% endblock %}

{% block navbar_right %}
    {% if l_session %}
        <li class="nav-item">
            <span class="nav-link status-session-name active">{{ l_session.name }}</span>
        </li>
    {% endif %}

    <li class="nav-item">
        <span class="nav-link status-connection" id="status">Not Connected</span>
    </li>
{% endblock %}

{% block js %}
    <script src="{{ url_for('static', filename='components/marked/marked.min.js') }}"></script>
    <script src="{{ url_for('static', filename='components/atrament/dist/atrament.min.js') }}"></script>
    <script src="{{ url_for('static', filename='colorPicker/colorPick.js') }}"></script>

    {% block blackboard_js %}
        {% assets "js_blackboard" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}
    {% endblock %}

    <script>
        $(document).ready(obbSocket.init({
            namespace: '/blackboard'
        }));
    </script>
{% endblock %}

src/obb/templates/blackboard/mode_blackboard.html
{% extends 'blackboard/layout.html' %}

{% block blackboard_js %}
    {% assets "js_blackboard_board" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}

{% block row %}
    <div class="row justify-content-center flex-grow-1 mt-2">
        <div class="col align-content-center">
            <div id="MainContent" class="PageContent" data-pageId="current">
            </div>

            <div data-for="MainContent" class="ContentToolBox CTB-2x mt-1">
            </div>
        </div>
    </div>
{% endblock %}

src/obb/templates/blackboard/mode_user.html
{% extends 'blackboard/layout.html' %}
{% from 'form.html' import show_form %}

{% block blackboard_js %}
    {% assets "js_blackboard_user" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}

{% block row %}
    <div class="row justify-content-center mt-3">
        <div class="col-6">
            <textarea id="MarkdownEditor" class="form-control" style="width: 100%;height: 20em"></textarea>

        </div>
        <div class="col-6">
            <div id="MainContent" class="PageContent" data-pageId="current">
            </div>

            <div data-for="MainContent" class="ContentToolBox mt-1">
            </div>
        </div>

    </div>
    <div class="row justify-content-center mt-3">
        <div class="col-4">
            <div class="card">
                <div class="card-header">Room</div>
                <div class="card-body">
                    <div>
                        <a href="{{ url_for('blackboard.lecture_download',lecture_id=l_session.lecture.id) }}"
                           target="_blank">
                            <i class="fas fa-download"></i>
                        </a>
                    </div>
                    <hr/>
                    {{ show_form(edit_form,id='roomEdit') }}
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">Clients</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Mode</th>
                            <th scope="col">Draw?</th>
                            <th scope="col">New Page?</th>
                            <th scope="col">Sync</th>
                        </tr>
                        </thead>
                        <tbody id="UserList">

                        </tbody>
                    </table>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/obb/templates/blackboard/rooms.html
{% extends 'blackboard/layout.html' %}
{% from 'form.html' import show_form %}

{% block row %}
    <div class="row justify-content-center">
        <div class="col mt-3">
            <div class="card">
                <div class="card-header">
                    Create
                </div>
                <div class="card-body">
                    {{ show_form(create_room_form,id='CreateRoom',action=url_for('blackboard.room_create')) }}

                    <hr/>

                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for room in rooms %}
                            <tr>
                                <th scope="row">{{ loop.index }}</th>
                                <td>
                                    <button class="btn btn-link p-0"
                                            onclick="$('#CreateLecture #room_name').val('{{ room.name }}')">
                                        {{ room.name }}
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col mt-3">
            <div class="card">
                <div class="card-header">Create Session</div>
                <div class="card-body">
                    {{ show_form(create_session_form,id='CreateLecture',action=url_for('blackboard.session_create')) }}
                </div>
            </div>
        </div>
        <div class="col mt-3">
            <div class="card">
                <div class="card-header">Lectures</div>
                <div class="card-body">

                    {{ show_form(create_lecture_form,id='CreateLecture',action=url_for('blackboard.lecture_create')) }}

                    <hr/>

                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for lecture in lectures %}
                            <tr>
                                <th scope="row">{{ loop.index }}</th>
                                <td>
                                    <button class="btn btn-link p-0"
                                            onclick="$('#CreateLecture #lecture_name').val('{{ lecture.name }}')">
                                        {{ lecture.name }}
                                    </button>
                                </td>
                                <td>
                                    <a href="{{ url_for('blackboard.lecture_edit',lecture_id=lecture.id) }}">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col mt-3">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                    <th scope="col">Open?</th>
                    <th scope="col">Room</th>
                    <th scope="col">Start-Time</th>
                    <th scope="col">End-Time</th>
                    <th scope="col">Duration</th>
                </tr>
                </thead>
                <tbody>
                {% for l_session in lecture_sessions %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td>
                            {%- if l_session.is_open() -%}
                                <a href="{{ url_for('blackboard.link_user',r=l_session.room_id) }}">{{ l_session.name }}</a>
                            {%- else -%}
                                {{ l_session.name }}
                            {%- endif -%}
                        </td>
                        <td>
                            <a href="#"><i class="fas fa-edit"></i></a>
                            <a href="#"><i class="fas fa-trash text-danger"></i></a>
                        </td>
                        <td><span
                                class="{{ 'is-open' if l_session.is_open() else 'is-close' }}">{{ 'Open' if l_session.is_open() else 'Closed' }}</span>
                        </td>
                        <td><a href="#">{{ l_session.room.name }}</a></td>
                        <td>{{ l_session.start_time | df }} </td>
                        <td>{{ l_session.end_time | df }} </td>
                        <td>{{ l_session.duration }} min</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}